const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
global.crypto=crypto.webcrypto;
const bundle=process.argv[2]||'openpgp.min.js';
vm.runInThisContext(fs.readFileSync('public/assets/'+bundle,'utf8'));
global.window={__forumBrowserIdentity:{ensureOpenPgpApi:async()=>openpgp}};
vm.runInThisContext(fs.readFileSync('public/assets/private_message_history_crypto.js','utf8'));
(async()=>{
 const c=window.ForumPrivateMessageHistoryCrypto;
 for(const text of ['', 'abc', '💡'.repeat(200), 'x'.repeat(10000)]) assert.equal(c.digest(text),crypto.createHash('sha256').update(text).digest('hex'));
 const gen=async(name)=>{const k=await openpgp.generateKey({type:'ecc',curve:'ed25519',userIDs:[{name}],format:'armored'});return {...k,fp:(await openpgp.readKey({armoredKey:k.publicKey})).getFingerprint().toLowerCase()};};
 const [sender,donor,target,later]=await Promise.all(['sender','donor','target','later'].map(gen));
 const original=async(signed)=>openpgp.encrypt({message:await openpgp.createMessage({text:'original secret'}),encryptionKeys:await openpgp.readKey({armoredKey:donor.publicKey}),...(signed?{signingKeys:await openpgp.readPrivateKey({armoredKey:sender.privateKey})}:{}),format:'armored'});
 const envelope=await original(true),keys=await c.extractKeys(envelope,donor.privateKey);
 await assert.rejects(()=>c.extractKeys(envelope,target.privateKey));
 const entry={message_id:'m1',digest:c.digest(envelope),keys};
 const binding={account:'alice',source:donor.fp,target:target.fp};
 const ciphertext=await c.wrapHistoryKeys({...binding,privateKey:donor.privateKey,targetKey:target.publicKey,entries:[entry]});
 const input={...binding,privateKey:target.privateKey,sourceKey:donor.publicKey,ciphertext};
 const restored=await c.unwrapHistoryKeys(input);
 assert.equal(restored[0].digest,c.digest(envelope));
 assert.equal(await c.readOriginal(envelope,restored[0].keys,[sender.publicKey]),'original secret');
 for(const bad of [{account:'mallory'},{source:sender.fp},{target:later.fp},{privateKey:later.privateKey},{sourceKey:sender.publicKey}]) await assert.rejects(()=>c.unwrapHistoryKeys({...input,...bad}));
 await assert.rejects(()=>c.readOriginal(envelope,restored[0].keys,[later.publicKey]));
 const unsigned=await original(false),unsignedKeys=await c.extractKeys(unsigned,donor.privateKey);
 await assert.rejects(()=>c.readOriginal(unsigned,unsignedKeys,[sender.publicKey]));
 const forwarded=await c.wrapHistoryKeys({account:'alice',source:target.fp,target:later.fp,privateKey:target.privateKey,targetKey:later.publicKey,entries:restored});
 const last=await c.unwrapHistoryKeys({account:'alice',source:target.fp,target:later.fp,privateKey:later.privateKey,sourceKey:target.publicKey,ciphertext:forwarded});
 assert.equal(await c.readOriginal(envelope,last[0].keys,[sender.publicKey]),'original secret');
 assert.notEqual(c.digest(envelope+'\n'),last[0].digest);
 // Cross-account bundles cannot be interpreted as v1 or rebound to another account.
 const crossBinding={...binding,source_account:'sender-account'};
 const crossCipher=await c.wrapHistoryKeys({...crossBinding,privateKey:donor.privateKey,targetKey:target.publicKey,entries:[entry]});
 const crossInput={...input,...crossBinding,ciphertext:crossCipher};
 const cross=await c.unwrapHistoryKeys(crossInput);
 assert.equal(await c.readOriginal(envelope,cross[0].keys,[sender.publicKey]),'original secret');
 for(const bad of [{source_account:'impostor'},{source_account:'alice'},{account:'impostor'},{ciphertext}]) await assert.rejects(()=>c.unwrapHistoryKeys({...crossInput,...bad}));
 await assert.rejects(()=>c.unwrapHistoryKeys({...input,ciphertext:crossCipher}));
 const altered=JSON.parse((await openpgp.decrypt({message:await openpgp.readMessage({armoredMessage:crossCipher}),decryptionKeys:await openpgp.readPrivateKey({armoredKey:target.privateKey}),format:'utf8'})).data);
 altered.purpose='recipient-to-sender';
 const wrongPurpose=await openpgp.encrypt({message:await openpgp.createMessage({text:JSON.stringify(altered)}),encryptionKeys:await openpgp.readKey({armoredKey:target.publicKey}),signingKeys:await openpgp.readPrivateKey({armoredKey:donor.privateKey}),format:'armored'});
 await assert.rejects(()=>c.unwrapHistoryKeys({...crossInput,ciphertext:wrongPurpose}));
 console.log(bundle+': real-key round trip, forwarding, binding/signature rejection, SHA-256 vectors passed');
})().catch(e=>{console.error(e);process.exit(1)});
